name: CI
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - run: ./gradlew build jacocoTestReport
      - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: report
          path: build/reports/jacoco/test/html/
          if-no-files-found: error
